project_identifier_env: CROWDIN_REACT_PROJECT_ID
api_key_env: CROWDIN_REACT_API_KEY
base_path: "./"
preserve_hierarchy: true

files:
  -
    source: '/content/docs/*.md'
    translation: '/content/i18n/%locale%/docs/%original_file_name%'
    languages_mapping: &anchor
      locale:
        # 'af': 'af' # Afrikaans
        'ar': 'ar' # Arabic
        # 'bs-BA': 'bs-BA' # Bosnian
        'bn': 'bn' # Bengali
        # 'ca': 'ca' #  Catalan
        'cs': 'cs' # Czech
        'da': 'da' # Danish
        'de': 'de' # German
        'el': 'el' # Greek
        'es-ES': 'es-ES' # Spanish
        'es-CO': 'es-CO' # Spanish, Colombia
        'es-MX': 'es-MX' # Spanish, Mezico
        # 'fa': 'fa-IR' # Persian
        # 'fi': 'fi' # Finnish
        'fr': 'fr' # French
        # 'he': 'he' # Hebrew
        'hu': 'hu' # Hungarian
        'id': 'id' # Indonesian
        'it': 'it' # Italian
        'ja': 'ja' # Japanese
        'ka': 'ka' # Georgian
        'ko': 'ko' # Korean
        'ku': 'ku' # Kurdish
        'ms': 'ms' # Malay
        # 'mr': 'mr-IN' # Marathi
        # 'nl': 'nl' # Dutch
        'no': 'no-NO' # Norwegian
        'pl': 'pl' # Polish
        'pt-BR': 'pt-BR' # Portuguese, Brazilian
        'pt-PT': 'pt-PT' # Portuguese
        'ro': 'ro' # Romanian
        'ru': 'ru' # Russian
        # 'sk': 'sk-SK' # Slovak
        'sl': 'sl' # Slovenian
        # 'sr': 'sr' # Serbian
        # 'sv-SE': 'sv-SE' # Swedish
        'tl': 'tl' # Tagalog
        'tr': 'tr' # Turkish
        # 'uk': 'uk' # Ukranian
        'ur-PK': 'ur-PK' # Urdu, Pakistan
        'vi': 'vi' # Vietnamese
        'zh-CN': 'zh-Hans' # Chinese Simplified
        'zh-TW': 'zh-Hant' # Chinese Traditional
  -
    source: '/content/*.yml'
    translation: '/content/i18n/%locale%/%original_file_name%'
    languages_mapping: *anchor
  -
    source: '/content/community/nav.yml'
    translation: '/content/i18n/%locale%/community/%original_file_name%'
    languages_mapping: *anchor
  -
    source: '/content/tutorial/nav.yml'
    translation: '/content/i18n/%locale%/tutorial/%original_file_name%'
    languages_mapping: *anchor
  -
    source: '/content/docs/nav.yml'
    translation: '/content/i18n/%locale%/docs/%original_file_name%'
    languages_mapping: *anchor
  -
    source: '/content/home/marketing/*.md'
    translation: '/content/i18n/%locale%/home/marketing/%original_file_name%'
    languages_mapping: *anchor
  -
    source: '/content/home/examples/*.md'
    translation: '/content/i18n/%locale%/home/examples/%original_file_name%'
    languages_mapping: *anchor
  -
    source: '/content/blog/*.md'
    translation: '/content/i18n/%locale%/blog/%original_file_name%'
    languages_mapping: *anchor
  -
    source: '/content/tutorial/*.md'
    translation: '/content/i18n/%locale%/tutorial/%original_file_name%'
    languages_mapping: *anchor
  -
    source: '/content/community/*.md'
    translation: '/content/i18n/%locale%/community/%original_file_name%'
    ignore:
      - '/content/community/complementary-tools.it-IT.md'
      - '/content/community/complementary-tools.ko-KR.md'
      - '/content/community/complementary-tools.zh-CN.md'
      - '/content/community/conferences.it-IT.md'
      - '/content/community/conferences.ko-KR.md'
      - '/content/community/conferences.zh-CN.md'
      - '/content/community/examples.it-IT.md'
      - '/content/community/examples.ko-KR.md'
      - '/content/community/examples.zh-CN.md'
      - '/content/community/videos.it-IT.md'
      - '/content/community/videos.ko-KR.md'
      - '/content/community/videos.zh-CN.md'
    languages_mapping: *anchor
  -
    source: '/content/contributing/*.md'
    translation: '/content/i18n/%locale%/contributing/%original_file_name%'
    languages_mapping: *anchor
  -
    source: '/content/warnings/*.md'
    translation: '/content/i18n/%locale%/warnings/%original_file_name%'
    languages_mapping: *anchor
  -
    source: '/README.md'
    translation: '/content/i18n/%locale%/README.md'
    languages_mapping: *anchor
  -
    source: '/content/404.md'
    translation: '/content/i18n/%locale%/404.md'
    languages_mapping: *anchor
